name: resourcelinker-sample-dependencies

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SA@sqlserver"
      MSSQL_PID: "Express"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    ports: 
      - 8080:8080
    volumes:
      - "./resourcelinker.sample-realm.json:/opt/keycloak/data/import/resourcelinker.sample-realm.json"
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


      

      